use everything_domain::{ConnectorActionDescriptor, ConnectorProvider, ConnectorRisk};
use serde_json::json;

#[derive(Debug, Clone)]
pub struct ProviderSpec {
    #[allow(dead_code)]
    pub provider: ConnectorProvider,
    pub display_name: &'static str,
    pub description: &'static str,
    pub authorization_endpoint: &'static str,
    pub token_endpoint: &'static str,
    #[allow(dead_code)]
    pub revoke_endpoint: Option<&'static str>,
    pub api_base: &'static str,
    pub default_scopes: &'static [&'static str],
    pub allowed_hosts: &'static [&'static str],
    pub limitations: &'static [&'static str],
    pub client_id_parameter: &'static str,
    pub scope_separator: &'static str,
    pub supports_pkce: bool,
    pub pkce_hex: bool,
    pub requires_client_secret: bool,
}

pub fn provider_spec(provider: ConnectorProvider) -> ProviderSpec {
    match provider {
        ConnectorProvider::Gmail => ProviderSpec {
            provider,
            display_name: "Gmail",
            description: "Read mailbox summaries and, when explicitly authorized, perform selected mail actions through the official Gmail API.",
            authorization_endpoint: "https://accounts.google.com/o/oauth2/v2/auth",
            token_endpoint: "https://oauth2.googleapis.com/token",
            revoke_endpoint: Some("https://oauth2.googleapis.com/revoke"),
            api_base: "https://gmail.googleapis.com/gmail/v1",
            default_scopes: &["https://www.googleapis.com/auth/gmail.readonly"],
            allowed_hosts: &[
                "accounts.google.com",
                "oauth2.googleapis.com",
                "gmail.googleapis.com",
            ],
            limitations: &[
                "Read-only scope is used by default; sending or modifying mail requires reconfiguration with narrower explicit scopes.",
                "Public applications requesting Gmail restricted scopes may require Google verification.",
                "Installed-app polling is used for local routines; Gmail Pub/Sub push requires cloud infrastructure.",
            ],
            client_id_parameter: "client_id",
            scope_separator: " ",
            supports_pkce: true,
            pkce_hex: false,
            requires_client_secret: false,
        },
        ConnectorProvider::Spotify => ProviderSpec {
            provider,
            display_name: "Spotify",
            description: "Inspect and control the active Spotify session through the official Web API.",
            authorization_endpoint: "https://accounts.spotify.com/authorize",
            token_endpoint: "https://accounts.spotify.com/api/token",
            revoke_endpoint: None,
            api_base: "https://api.spotify.com/v1",
            default_scopes: &[
                "user-read-private",
                "user-read-playback-state",
                "user-read-currently-playing",
                "playlist-read-private",
            ],
            allowed_hosts: &["accounts.spotify.com", "api.spotify.com"],
            limitations: &[
                "Playback-control endpoints require Spotify Premium.",
                "Development-mode applications may have an allowlisted-user cap.",
                "Playback commands require reconnecting with user-modify-playback-state and are approval-gated by default.",
            ],
            client_id_parameter: "client_id",
            scope_separator: " ",
            supports_pkce: true,
            pkce_hex: false,
            requires_client_secret: false,
        },
        ConnectorProvider::TikTok => ProviderSpec {
            provider,
            display_name: "TikTok",
            description: "Read creator information and initialize official Content Posting API jobs.",
            authorization_endpoint: "https://www.tiktok.com/v2/auth/authorize/",
            token_endpoint: "https://open.tiktokapis.com/v2/oauth/token/",
            revoke_endpoint: Some("https://open.tiktokapis.com/v2/oauth/revoke/"),
            api_base: "https://open.tiktokapis.com",
            default_scopes: &["user.info.basic", "video.list"],
            allowed_hosts: &[
                "www.tiktok.com",
                "open.tiktokapis.com",
                "open-upload.tiktokapis.com",
            ],
            limitations: &[
                "Direct posting requires reconnecting with video.publish, TikTok app approval, and explicit creator consent.",
                "Unaudited clients are restricted to private-viewing posts.",
                "PULL_FROM_URL media must come from a verified domain or URL prefix.",
            ],
            client_id_parameter: "client_key",
            scope_separator: ",",
            supports_pkce: true,
            pkce_hex: true,
            requires_client_secret: true,
        },
        ConnectorProvider::Instagram => ProviderSpec {
            provider,
            display_name: "Instagram",
            description: "Read professional account media and publish media through the official Instagram Platform.",
            authorization_endpoint: "https://www.instagram.com/oauth/authorize",
            token_endpoint: "https://api.instagram.com/oauth/access_token",
            revoke_endpoint: None,
            api_base: "https://graph.instagram.com",
            default_scopes: &["instagram_business_basic"],
            allowed_hosts: &[
                "www.instagram.com",
                "api.instagram.com",
                "graph.instagram.com",
                "graph.facebook.com",
            ],
            limitations: &[
                "Publishing requires reconnecting with instagram_business_content_publish and is limited to eligible professional accounts with approved app permissions.",
                "Media URLs must be publicly reachable by Meta during container creation.",
                "Publishing is a two-step container creation and media_publish operation.",
            ],
            client_id_parameter: "client_id",
            scope_separator: ",",
            supports_pkce: false,
            pkce_hex: false,
            requires_client_secret: true,
        },
        ConnectorProvider::GitHub => ProviderSpec {
            provider,
            display_name: "GitHub",
            description: "Inspect and operate repositories, issues, pull requests, Actions, releases, notifications, REST endpoints, and GraphQL through the official GitHub APIs.",
            authorization_endpoint: "https://github.com/login/oauth/authorize",
            token_endpoint: "https://github.com/login/oauth/access_token",
            revoke_endpoint: None,
            api_base: "https://api.github.com",
            default_scopes: &["read:user"],
            allowed_hosts: &["github.com", "api.github.com", "uploads.github.com"],
            limitations: &[
                "Fine-grained personal access tokens are recommended for local use and should be restricted to the minimum repositories and permissions.",
                "Every mutating REST or GraphQL operation is approval-gated and requires an idempotency key.",
                "Repository rules, branch protection, organization policy, SSO, token permissions, and rate limits remain authoritative.",
            ],
            client_id_parameter: "client_id",
            scope_separator: " ",
            supports_pkce: false,
            pkce_hex: false,
            requires_client_secret: false,
        },
        ConnectorProvider::Custom => ProviderSpec {
            provider,
            display_name: "Custom HTTP",
            description: "Operator-defined HTTPS connector with strict host and action allowlists.",
            authorization_endpoint: "",
            token_endpoint: "",
            revoke_endpoint: None,
            api_base: "",
            default_scopes: &[],
            allowed_hosts: &[],
            limitations: &[
                "Custom connectors are disabled by default and require explicit runtime configuration.",
            ],
            client_id_parameter: "client_id",
            scope_separator: " ",
            supports_pkce: false,
            pkce_hex: false,
            requires_client_secret: false,
        },
    }
}

pub fn builtin_actions(provider: ConnectorProvider) -> Vec<ConnectorActionDescriptor> {
    match provider {
        ConnectorProvider::Gmail => vec![
            action(
                "profile",
                "Mailbox profile",
                "Read mailbox totals and account address.",
                ConnectorRisk::ReadOnly,
                &["https://www.googleapis.com/auth/gmail.readonly"],
                json!({"type":"object","additionalProperties":false}),
                true,
                true,
            ),
            action(
                "unread_summary",
                "Unread summary",
                "List unread message identifiers using Gmail search syntax.",
                ConnectorRisk::ReadOnly,
                &["https://www.googleapis.com/auth/gmail.readonly"],
                json!({"type":"object","properties":{"query":{"type":"string","maxLength":2048},"max_results":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "latest_messages",
                "Latest messages",
                "Fetch selected message metadata for recent matching messages.",
                ConnectorRisk::ReadOnly,
                &["https://www.googleapis.com/auth/gmail.readonly"],
                json!({"type":"object","properties":{"query":{"type":"string","maxLength":2048},"max_results":{"type":"integer","minimum":1,"maximum":20}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "mark_read",
                "Mark message read",
                "Remove the UNREAD label from one Gmail message.",
                ConnectorRisk::ReversibleWrite,
                &["https://www.googleapis.com/auth/gmail.modify"],
                json!({"type":"object","required":["message_id"],"properties":{"message_id":{"type":"string","minLength":1,"maxLength":256}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "archive",
                "Archive message",
                "Remove the INBOX label from one Gmail message.",
                ConnectorRisk::ReversibleWrite,
                &["https://www.googleapis.com/auth/gmail.modify"],
                json!({"type":"object","required":["message_id"],"properties":{"message_id":{"type":"string","minLength":1,"maxLength":256}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "send_email",
                "Send email",
                "Send a plain-text email through the official Gmail API.",
                ConnectorRisk::ExternalPublish,
                &["https://www.googleapis.com/auth/gmail.send"],
                json!({"type":"object","required":["to","subject","body"],"properties":{"to":{"type":"string","minLength":3,"maxLength":2048},"cc":{"type":"string","maxLength":2048},"bcc":{"type":"string","maxLength":2048},"subject":{"type":"string","maxLength":998},"body":{"type":"string","maxLength":200000},"reply_to_message_id":{"type":"string","maxLength":256},"thread_id":{"type":"string","maxLength":256}},"additionalProperties":false}),
                true,
                false,
            ),
        ],
        ConnectorProvider::Spotify => vec![
            action(
                "profile",
                "Spotify profile",
                "Read the current Spotify profile.",
                ConnectorRisk::ReadOnly,
                &["user-read-private"],
                json!({"type":"object"}),
                true,
                true,
            ),
            action(
                "playback",
                "Playback state",
                "Read the currently active device and item.",
                ConnectorRisk::ReadOnly,
                &["user-read-playback-state"],
                json!({"type":"object"}),
                true,
                true,
            ),
            action(
                "play",
                "Play or resume",
                "Start or resume playback on the active device.",
                ConnectorRisk::AccountMutation,
                &["user-modify-playback-state"],
                json!({"type":"object","properties":{"device_id":{"type":"string"},"uri":{"type":"string"}}}),
                true,
                false,
            ),
            action(
                "pause",
                "Pause",
                "Pause the active Spotify playback.",
                ConnectorRisk::AccountMutation,
                &["user-modify-playback-state"],
                json!({"type":"object","properties":{"device_id":{"type":"string"}}}),
                true,
                false,
            ),
            action(
                "next",
                "Next track",
                "Skip to the next item.",
                ConnectorRisk::AccountMutation,
                &["user-modify-playback-state"],
                json!({"type":"object","properties":{"device_id":{"type":"string"}}}),
                true,
                false,
            ),
            action(
                "previous",
                "Previous track",
                "Skip to the previous item.",
                ConnectorRisk::AccountMutation,
                &["user-modify-playback-state"],
                json!({"type":"object","properties":{"device_id":{"type":"string"}}}),
                true,
                false,
            ),
            action(
                "queue",
                "Add to queue",
                "Add a Spotify URI to the active playback queue.",
                ConnectorRisk::ReversibleWrite,
                &["user-modify-playback-state"],
                json!({"type":"object","required":["uri"],"properties":{"uri":{"type":"string"},"device_id":{"type":"string"}}}),
                true,
                false,
            ),
        ],
        ConnectorProvider::TikTok => vec![
            action(
                "profile",
                "TikTok profile",
                "Read the authorized creator profile.",
                ConnectorRisk::ReadOnly,
                &["user.info.basic"],
                json!({"type":"object"}),
                true,
                true,
            ),
            action(
                "videos",
                "Recent TikTok videos",
                "Read metadata for recently uploaded videos.",
                ConnectorRisk::ReadOnly,
                &["video.list"],
                json!({"type":"object","properties":{"max_count":{"type":"integer","minimum":1,"maximum":20}}}),
                true,
                true,
            ),
            action(
                "creator_info",
                "Publishing capabilities",
                "Read current privacy and interaction options before posting.",
                ConnectorRisk::ReadOnly,
                &["video.publish"],
                json!({"type":"object"}),
                true,
                true,
            ),
            action(
                "publish_video_url",
                "Publish video URL",
                "Initialize a direct post from a verified public URL.",
                ConnectorRisk::ExternalPublish,
                &["video.publish"],
                json!({"type":"object","required":["video_url","privacy_level"],"properties":{"video_url":{"type":"string"},"privacy_level":{"type":"string"},"title":{"type":"string"},"disable_comment":{"type":"boolean"},"disable_duet":{"type":"boolean"},"disable_stitch":{"type":"boolean"},"is_aigc":{"type":"boolean"}}}),
                true,
                false,
            ),
            action(
                "publish_status",
                "Publishing status",
                "Fetch processing state for a TikTok publish identifier.",
                ConnectorRisk::ReadOnly,
                &["video.publish"],
                json!({"type":"object","required":["publish_id"],"properties":{"publish_id":{"type":"string"}}}),
                true,
                true,
            ),
        ],
        ConnectorProvider::Instagram => vec![
            action(
                "profile",
                "Instagram profile",
                "Read professional-account profile fields.",
                ConnectorRisk::ReadOnly,
                &["instagram_business_basic"],
                json!({"type":"object"}),
                true,
                true,
            ),
            action(
                "media",
                "Instagram media",
                "List recent media metadata.",
                ConnectorRisk::ReadOnly,
                &["instagram_business_basic"],
                json!({"type":"object","properties":{"limit":{"type":"integer","minimum":1,"maximum":50}}}),
                true,
                true,
            ),
            action(
                "publish_image_url",
                "Publish image URL",
                "Create and publish an Instagram image container.",
                ConnectorRisk::ExternalPublish,
                &["instagram_business_content_publish"],
                json!({"type":"object","required":["image_url"],"properties":{"image_url":{"type":"string"},"caption":{"type":"string"}}}),
                true,
                false,
            ),
        ],
        ConnectorProvider::GitHub => vec![
            action(
                "profile",
                "GitHub profile",
                "Read the authenticated GitHub account and API rate-limit metadata.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","additionalProperties":false}),
                true,
                true,
            ),
            action(
                "repository",
                "Repository",
                "Read repository metadata, permissions, default branch, and security settings visible to the token.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo"],"properties":{"owner":{"type":"string","minLength":1,"maxLength":100},"repo":{"type":"string","minLength":1,"maxLength":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "search_code",
                "Search code",
                "Search code through GitHub's official search API.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["query"],"properties":{"query":{"type":"string","minLength":1,"maxLength":4096},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "issues",
                "Issues",
                "List repository issues with bounded pagination.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"state":{"type":"string"},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "pull_requests",
                "Pull requests",
                "List repository pull requests.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"state":{"type":"string"},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "notifications",
                "Notifications",
                "Read GitHub notifications visible to the token.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","properties":{"all":{"type":"boolean"},"participating":{"type":"boolean"},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "workflow_runs",
                "Workflow runs",
                "List recent GitHub Actions workflow runs.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "branches",
                "Branches",
                "List repository branches with bounded pagination.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "commits",
                "Commits",
                "List repository commits, optionally filtered by ref or path.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"sha":{"type":"string"},"path":{"type":"string"},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "releases",
                "Releases",
                "List repository releases.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "contents",
                "Repository contents",
                "Read a file or directory through GitHub's contents API.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","path"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"path":{"type":"string","minLength":1,"maxLength":4096},"ref":{"type":"string"}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "security_alerts",
                "Security alerts",
                "Read Dependabot, code-scanning, or secret-scanning alerts visible to the token.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","kind"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"kind":{"type":"string","enum":["dependabot","code_scanning","secret_scanning"]},"state":{"type":"string"},"per_page":{"type":"integer","minimum":1,"maximum":100}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "rest_read",
                "GitHub REST read",
                "Call any allowlisted GitHub REST GET endpoint with bounded query parameters.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["path"],"properties":{"path":{"type":"string","minLength":1,"maxLength":4096},"query":{"type":"object"}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "graphql_read",
                "GitHub GraphQL read",
                "Execute a query-only GitHub GraphQL document.",
                ConnectorRisk::ReadOnly,
                &["github:token"],
                json!({"type":"object","required":["query"],"properties":{"query":{"type":"string","minLength":1,"maxLength":200000},"variables":{"type":"object"}},"additionalProperties":false}),
                true,
                true,
            ),
            action(
                "create_issue",
                "Create issue",
                "Create a GitHub issue.",
                ConnectorRisk::ExternalPublish,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","title"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"title":{"type":"string","minLength":1,"maxLength":256},"body":{"type":"string","maxLength":200000},"labels":{"type":"array"},"assignees":{"type":"array"}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "comment_issue",
                "Comment on issue or pull request",
                "Create a GitHub issue or pull-request conversation comment.",
                ConnectorRisk::ExternalPublish,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","number","body"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"number":{"type":"integer","minimum":1},"body":{"type":"string","minLength":1,"maxLength":200000}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "create_pull_request",
                "Create pull request",
                "Open a pull request from a head ref to a base ref.",
                ConnectorRisk::ExternalPublish,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","title","head","base"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"title":{"type":"string"},"head":{"type":"string"},"base":{"type":"string"},"body":{"type":"string"},"draft":{"type":"boolean"}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "merge_pull_request",
                "Merge pull request",
                "Merge a pull request using an explicit merge method.",
                ConnectorRisk::AccountMutation,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","number"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"number":{"type":"integer","minimum":1},"commit_title":{"type":"string"},"commit_message":{"type":"string"},"merge_method":{"type":"string"}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "workflow_dispatch",
                "Dispatch workflow",
                "Trigger a GitHub Actions workflow on a selected ref.",
                ConnectorRisk::AccountMutation,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","workflow","ref"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"workflow":{"type":"string"},"ref":{"type":"string"},"inputs":{"type":"object"}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "create_release",
                "Create release",
                "Create a draft or published GitHub release.",
                ConnectorRisk::ExternalPublish,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","tag_name"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"tag_name":{"type":"string"},"target_commitish":{"type":"string"},"name":{"type":"string"},"body":{"type":"string","maxLength":200000},"draft":{"type":"boolean"},"prerelease":{"type":"boolean"},"generate_release_notes":{"type":"boolean"}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "mark_notification_read",
                "Mark notification read",
                "Mark one GitHub notification thread as read.",
                ConnectorRisk::AccountMutation,
                &["github:token"],
                json!({"type":"object","required":["thread_id"],"properties":{"thread_id":{"type":"string","minLength":1,"maxLength":128}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "rerun_workflow",
                "Re-run workflow",
                "Re-run a GitHub Actions workflow run.",
                ConnectorRisk::AccountMutation,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","run_id"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"run_id":{"type":"integer","minimum":1}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "cancel_workflow",
                "Cancel workflow",
                "Cancel an in-progress GitHub Actions workflow run.",
                ConnectorRisk::AccountMutation,
                &["github:token"],
                json!({"type":"object","required":["owner","repo","run_id"],"properties":{"owner":{"type":"string"},"repo":{"type":"string"},"run_id":{"type":"integer","minimum":1}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "rest_write",
                "GitHub REST mutation",
                "Call any allowlisted mutating GitHub REST endpoint after explicit approval.",
                ConnectorRisk::AccountMutation,
                &["github:token"],
                json!({"type":"object","required":["method","path"],"properties":{"method":{"type":"string"},"path":{"type":"string","minLength":1,"maxLength":4096},"query":{"type":"object"},"body":{}},"additionalProperties":false}),
                true,
                false,
            ),
            action(
                "graphql_mutation",
                "GitHub GraphQL mutation",
                "Execute an explicitly approved GitHub GraphQL mutation.",
                ConnectorRisk::AccountMutation,
                &["github:token"],
                json!({"type":"object","required":["query"],"properties":{"query":{"type":"string","minLength":1,"maxLength":200000},"variables":{"type":"object"}},"additionalProperties":false}),
                true,
                false,
            ),
        ],
        ConnectorProvider::Custom => Vec::new(),
    }
}

#[allow(clippy::too_many_arguments)]
fn action(
    action_id: &str,
    title: &str,
    description: &str,
    risk: ConnectorRisk,
    scopes: &[&str],
    input_schema: serde_json::Value,
    supports_dry_run: bool,
    idempotent: bool,
) -> ConnectorActionDescriptor {
    ConnectorActionDescriptor {
        action_id: action_id.to_owned(),
        title: title.to_owned(),
        description: description.to_owned(),
        risk,
        required_scopes: scopes.iter().map(|scope| (*scope).to_owned()).collect(),
        input_schema,
        supports_dry_run,
        idempotent,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn provider_defaults_are_read_only_or_profile_scoped() {
        let spotify = provider_spec(ConnectorProvider::Spotify);
        assert!(
            !spotify
                .default_scopes
                .contains(&"user-modify-playback-state")
        );
        assert!(!spotify.default_scopes.contains(&"playlist-modify-private"));

        let tiktok = provider_spec(ConnectorProvider::TikTok);
        assert!(!tiktok.default_scopes.contains(&"video.publish"));

        let instagram = provider_spec(ConnectorProvider::Instagram);
        assert!(
            !instagram
                .default_scopes
                .contains(&"instagram_business_content_publish")
        );
    }

    #[test]
    fn mutating_actions_declare_explicit_scopes() {
        for provider in [
            ConnectorProvider::Gmail,
            ConnectorProvider::Spotify,
            ConnectorProvider::TikTok,
            ConnectorProvider::Instagram,
            ConnectorProvider::GitHub,
        ] {
            for action in builtin_actions(provider) {
                if action.risk != ConnectorRisk::ReadOnly {
                    assert!(
                        !action.required_scopes.is_empty(),
                        "mutating connector action {} must declare a scope",
                        action.action_id
                    );
                }
            }
        }
    }
}
